repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.0.0-1
    hooks:
        -   id: blacken-docs
            additional_dependencies: [black]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.5.0
    hooks:
        -   id: reorder-python-imports
