language: python
python:
    - 3.7
    - 3.6
    - 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: michaelbilow
  password:
    secure: fSsksCZscdLVB1MDhCmV/AS+RiBiIdz3v0RxdZD4s2YoquRATpvynhVVC1GN7HvlwX3Wd5anA5vPTBLC8aNpJG5c9m0+/79VIl4L6X4QiuWc5OewkkntTz8CcTVZ13btE77CzSELPz+lXGNl5tv+PJ8MnqxS7M2gP6XRSbE8r+1mzNVxm3wmk2WNI6rJEkf9ICGDpWE2ky/PdOOhmfi0HEYpT3KR+LRN65D1B29oy69kSMUfJ02rrB2e2RGRs/4uEuDnK8+vT/fch7n6UhBTOQxj2NEUKevVsA6sY+0715v2HV998v39dmT9U/1YZ97j0nO6fOtGfmcvP2sGFK0U+Xg5vhBVH2H0D9DAjwm4ObLMuSJFsBw3MAcGGjofDTgGUIlQoRXhBSe23ejt52aleG7Wj7wCAD029Dz4iC83WENPwWG4a5yb1AOwJOh+QbqsHEFcIM/8dhOVgRLiSqmjn1tKVX8xRMdLZAj1GBGJpymy/EB8irFIPbCByQ2jRUpHqud10hKCJrmhIE7IW7OJ5mxswk9E2KlSiGZmb8rUD1R1c2U7atTTwlqffY4Xv4NMbf+CG2oIODQ619/fX/NKN7h4YNWPdJxRmQmMaZdC/fSpLOmtxMDo6Cj2bm+hN94andUO0clWxR9+d1GC3r8Wmk2bdj1q6n8lF3MRA2HSxi0=
  on:
    tags: true
    repo: michaelbilow/issho
    python: 3.5
